trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  publishDirectory: '$(build.artifactStagingDirectory)/publish'

jobs:
- job: Build
  displayName: 'Build and Publish ASP.NET Core Solution'
  steps:
  - task: NuGetToolInstaller@1  # Ensure NuGet is installed

  - task: NuGetCommand@2  # Restore NuGet packages
    inputs:
      restoreSolution: '$(solution)'

  - task: DotNetCoreCLI@2  # Use .NET CLI to build and publish the project to a specific folder
    inputs:
      command: 'publish'
      projects: '$(solution)'  # Target the specific solution/project
      arguments: '--output $(publishDirectory) --configuration $(buildConfiguration)'

  - task: PublishBuildArtifacts@1  # Publish the build artifact without compressing it into a zip
    inputs:
      pathToPublish: '$(publishDirectory)'  # Publish the entire folder as an artifact
      artifactName: 'PublishArtifacts'  # Name for the published artifact
      publishLocation: 'Container'  # Publish to the Azure DevOps artifact container
      artifactType: 'folder'  # Ensure the artifact is treated as a folder

- job: CopyOutput
  displayName: 'Copy Published Files to IIS'
  dependsOn: Build  # This job runs only if the build is successful
  pool:
    name: 'jaison'

  steps:
  - task: DownloadBuildArtifacts@0  # Download the published build artifact
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'PublishArtifacts'  # Name of the artifact to download
      downloadPath: '$(Pipeline.Workspace)'

  - task: PowerShell@2  # Copy the published files to a specific IIS location
    inputs:
      targetType: 'inline'
      script: |
        $sourcePath = "$(Pipeline.Workspace)/PublishArtifacts"  # Location of downloaded build artifact
        $targetPath = 'C:\azuredevops'  # Desired copy location

        # Ensure the target directory exists
        if (-not (Test-Path $targetPath)) {
          New-Item -Path $targetPath -ItemType Directory
        }

        # Copy the published files to the specified location
        Copy-Item -Path $sourcePath/* -Destination $targetPath -Recurse -Force
