trigger:
- master

pool:
  vmImage: 'windows-latest'
  
steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'RDPazure'
    sourceFolder: 'C:\Users\devopstest\Documents\test1\'
    contents: '**'
    targetFolder: 'C:\Users\devopstest\Downloads\'
    isWindowsOnTarget: true
    readyTimeout: '20000'
