trigger:
- main

pool:
  vmImage: 'windows-latest'  # Using a Windows-hosted agent pool

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  publishDirectory: '$(build.artifactStagingDirectory)/publish'

jobs:
- job: Build
  displayName: 'Build and Publish ASP.NET Core Solution'
  steps:
  - task: NuGetToolInstaller@1  # Ensure NuGet is installed

  - task: NuGetCommand@2  # Restore NuGet packages
    inputs:
      restoreSolution: '$(solution)'

  - task: DotNetCoreCLI@2  # Use the .NET CLI to build and publish
    inputs:
      command: 'publish'
      projects: '$(solution)'
      arguments: '--output $(publishDirectory) --configuration $(buildConfiguration)'  # Publish to folder
      noBuild: true  # Avoid re-building

  - task: PublishBuildArtifacts@1  # Publish the folder-based build artifact
    inputs:
      pathToPublish: '$(publishDirectory)'
      artifactName: 'PublishArtifacts'  # Name for the published artifact
      publishLocation: 'Container'  # Publish to the Azure DevOps artifact container

- job: CopyOutput
  displayName: 'Copy Published Files to C drive'
  dependsOn: Build  # This job runs only if the build is successful
  pool:
    name: 'jaison'

  steps:
  - task: DownloadBuildArtifacts@0  # Download the build artifact
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'PublishArtifacts'  # Name of the artifact to download
      downloadPath: '$(Pipeline.Workspace)'

  - task: PowerShell@2  # Copy the published files to the specific location
    inputs:
      targetType: 'inline'
      script: |
        $sourcePath = "$(Pipeline.Workspace)/PublishArtifacts"  # Downloaded build artifact
        $targetPath = 'c:\azuredevops'  # Desired copy location

        # Ensure the target directory exists
        if (-not (Test-Path $targetPath)) {
          New-Item -Path $targetPath -ItemType Directory
        }

        # Copy the published files to the specified location
        Copy-Item -Path $sourcePath/* -Destination $targetPath -Recurse -Force
