trigger:
- master

pool:
  vmImage: 'windows-latest'
  

variables:
  # These should be secured and stored in Azure DevOps (like in variable groups)
  rdp_user: 'devopstest'
  rdp_password: '9Hm45uI>d>1x'  # Securely store this variable in Azure DevOps
  remote_server: '137.117.121.209'

jobs:
- job: CopyFilesWithinRemoteServer
  displayName: 'Copy Files Within Remote Server'
  steps:
  - task: PowerShell@2
    displayName: 'Copy Folder with PowerShell Remoting'
    inputs:
      targetType: 'inline'
      script: |
        # Securely handle credentials for PowerShell Remoting
        $password = ConvertTo-SecureString -String "$(rdp_password)" -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential -ArgumentList "$(rdp_user)", $password

        # Establish a remote session to the Windows server
        $session = New-PSSession -ComputerName "$(remote_server)" -Credential $credential

        # Copy files within the remote server
        Invoke-Command -Session $session -ScriptBlock {
          $source = 'C:\Users\devopstest\Documents\test1\'  # Update with your source path
          $destination = 'C:\Users\devopstest\Downloads\'  # Update with your destination path

          # Copy the folder recursively
          Copy-Item -Path $source -Destination $destination -Recurse -Force
        }

        # Close the remote session
        Remove-PSSession -Session $session